import { Contact, H2, LegalPage, Operator } from '@/components/LegalPage';

export const metadata = { title: 'Terms of Service · ReelCraft' };

export default function Terms() {
  return (
    <LegalPage title="Terms of Service" updated="October 5, 2026">
      <p>
        These terms apply when you use ReelCraft, operated by <Operator />. By signing in or using the service you agree to them. If you do
        not agree, please do not use ReelCraft.
      </p>

      <H2>The service</H2>
      <p>
        ReelCraft helps you turn your video clips into a captioned vertical video. Video processing happens on your device. We provide the
        sign-in, usage limits and AI caption generation. The service is free, provided as is, and may change, be limited or be unavailable at any time.
      </p>

      <H2>Your content and your responsibility</H2>
      <ul className="list-disc space-y-1 pl-5">
        <li>You keep ownership of your videos and of the reels you make. We do not receive your videos and claim no rights to them.</li>
        <li>You must have the right to use everything you add, including video, music in your clips, and the people shown in them.</li>
        <li>
          Because your videos never reach our servers, we cannot review them. You alone are responsible for what you create and share.
        </li>
        <li>
          Do not use ReelCraft to create or share anything unlawful, including sexual content involving minors, content that exploits or
          harasses others, recordings made without the consent the law requires, or content that infringes someone else&apos;s rights.
        </li>
        <li>Do not misuse the service: no automated access, no attempts to bypass usage limits, no interference with the service or other users.</li>
      </ul>

      <H2>AI captions</H2>
      <p>
        Captions are generated by an AI model and can be inaccurate or unsuitable. Review them before you publish. Each account has a daily
        limit of AI caption runs, and the service as a whole has a daily capacity, so a run may sometimes be unavailable.
      </p>

      <H2>Accounts</H2>
      <p>You sign in with a Google account. Keep it secure. We may suspend access for misuse or to protect the service.</p>

      <H2>Disclaimers and liability</H2>
      <p>
        To the extent the law allows, the service is provided without warranties of any kind, and <Operator /> is not liable for indirect or
        consequential damages or for lost content. Some places do not allow these limits, so they may not apply to you.
      </p>

      <H2>Changes and contact</H2>
      <p>
        We may update these terms and will post the new version here. Questions: <Contact />.
      </p>
    </LegalPage>
  );
}
